- name: Nginx-install
  become: true
  hosts: all


  tasks:
    - name: Add the user 'jp' and add it to 'sudo'
      ansible.builtin.user:
        name: jp
        group: sudo

    - name: Add SSH key to 'sammy'
      ansible.posix.authorized_key:
        user: jp
        state: present
        key: "{{ lookup('file', hcloud_ssh_key) }}"
